# Generated by Django 5.1.5 on 2025-01-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_game_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
