# Generated by Django 5.1.4 on 2025-01-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
